package com.alicejump.okscripttoolkit.core

import com.alicejump.okscripttoolkit.settings.OkScriptToolkitSettings
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

/** 框和点在最终 PositionMap 命名空间中的统一运行时表示。 */
object PositionResource {
    enum class Kind { RECT, POINT }
    data class Image(val file: String, val width: Int, val height: Int)
    data class Item(
        val path: String,
        val image: String,
        val kind: Kind,
        val x: Int,
        val y: Int,
        val w: Int = 0,
        val h: Int = 0,
    )
    data class RuntimePosition(val path: String, val coordinates: List<Double>)
    data class PublishResult(val positions: List<RuntimePosition>, val errors: List<String>)

    private const val DECIMALS = 6
    const val GENERATED_MARKER = "# Generated by ok-script-toolkit. Do not edit manually."

    fun publish(items: List<Item>, images: List<Image>): PublishResult {
        val errors = mutableListOf<String>()
        val positions = mutableListOf<RuntimePosition>()
        val seen = mutableSetOf<String>()
        val imageMap = images.associateBy { it.file.lowercase(Locale.ROOT) }
        for (item in items) {
            val path = item.path.trim()
            val pathError = PointCatalogService.positionPathError(path)
            if (pathError != null) { errors += "$pathError:$path"; continue }
            if (!seen.add(path)) { errors += "duplicate:$path"; continue }
            if (seen.any { it != path && (it.startsWith("$path.") || path.startsWith("$it.")) }) {
                errors += "prefix:$path"
                continue
            }
            val image = imageMap[item.image.lowercase(Locale.ROOT)]
            if (image == null) { errors += "image:$path"; continue }
            val coordinates = when (item.kind) {
                Kind.POINT -> normalizePoint(item.x, item.y, image.width, image.height)
                Kind.RECT -> normalizeRect(item.x, item.y, item.w, item.h, image.width, image.height)
            }
            if (coordinates == null) { errors += "geometry:$path"; continue }
            positions += RuntimePosition(path, coordinates)
        }
        return PublishResult(positions.sortedBy { it.path }, errors)
    }

    fun normalizePoint(x: Int, y: Int, width: Int, height: Int): List<Double>? {
        if (width <= 0 || height <= 0 || x < 0 || y < 0 || x > width || y > height) return null
        return listOf(round(x.toDouble() / width), round(y.toDouble() / height))
    }

    fun normalizeRect(x: Int, y: Int, w: Int, h: Int, width: Int, height: Int): List<Double>? {
        if (width <= 0 || height <= 0 || w <= 0 || h <= 0 || x < 0 || y < 0 || x + w > width || y + h > height) return null
        return listOf(
            round(x.toDouble() / width),
            round(y.toDouble() / height),
            round((x + w).toDouble() / width),
            round((y + h).toDouble() / height),
        )
    }

    fun serializeJson(result: PublishResult): String {
        val mapper = ObjectMapper()
        val root = mapper.createObjectNode().put("version", 2)
        val array = mapper.createArrayNode()
        result.positions.sortedBy { it.path }.forEach { position ->
            val node = mapper.createObjectNode().put("path", position.path)
            val coords = mapper.createArrayNode()
            position.coordinates.forEach(coords::add)
            node.set<JsonNode>("coordinates", coords)
            array.add(node)
        }
        root.set<JsonNode>("positions", array)
        return root.toPrettyString() + "\n"
    }

    fun serializeScreenRatioPython(): String = """$GENERATED_MARKER
from typing import TYPE_CHECKING, Iterator

if TYPE_CHECKING:
    from ok import Box


class ScreenRatio:
    \"\"\"A normalized screen point (x, y) or rectangle (left, top, right, bottom).\"\"\"

    def __init__(self, *coordinates: float):
        if len(coordinates) not in (2, 4):
            raise ValueError(\"ScreenRatio requires either 2 point coordinates or 4 rect coordinates\")
        self.coordinates = tuple(coordinates)
        self.name: str | None = None

    def __set_name__(self, owner: type, field_name: str):
        self.name = f\"{owner.__name__}.{field_name}\"

    def __get__(self, instance, owner):
        if instance is None:
            return self
        return BoundScreenRatio(self, instance._parent)

    def __iter__(self) -> Iterator[float]:
        return iter(self.coordinates)

    @property
    def is_rect(self) -> bool:
        return len(self.coordinates) == 4

    def _to_box(self, parent) -> \"Box\":
        if not self.is_rect:
            raise ValueError(\"Only a rect ScreenRatio can be converted to a Box\")
        return parent.box_of_screen(*self.coordinates, name=self.name or \"ScreenRatio\", hcenter=True)


class BoundScreenRatio:
    def __init__(self, ratio: ScreenRatio, parent):
        self.ratio = ratio
        self.parent = parent

    def __iter__(self) -> Iterator[float]:
        return iter(self.ratio)

    def to_box(self) -> \"Box\":
        return self.ratio._to_box(self.parent)
""".trimIndent() + "\n"

    fun serializePositionMapPython(result: PublishResult): String {
        val root = Node()
        for (position in result.positions.sortedBy { it.path }) {
            var node = root
            position.path.split('.').forEach { part -> node = node.children.getOrPut(part) { Node() } }
            node.coordinates = position.coordinates
        }
        val out = mutableListOf(
            GENERATED_MARKER,
            "from .ScreenRatio import ScreenRatio",
            "",
            "",
        )
        val emitted = mutableSetOf<String>()
        root.children.toSortedMap().forEach { (name, child) -> emitClass(child, listOf(name), out, emitted) }
        out += "class PositionMap:"
        out += "    def __init__(self, parent):"
        if (root.children.isEmpty()) out += "        pass"
        else root.children.toSortedMap().forEach { (name, _) -> out += "        self.$name = ${className(listOf(name))}(parent)" }
        out += ""
        return out.joinToString("\n") + "\n"
    }

    private data class Node(val children: MutableMap<String, Node> = mutableMapOf(), var coordinates: List<Double>? = null)

    private fun emitClass(node: Node, parts: List<String>, out: MutableList<String>, emitted: MutableSet<String>) {
        val className = className(parts)
        if (className in emitted) return
        node.children.toSortedMap().forEach { (name, child) ->
            if (child.children.isNotEmpty()) emitClass(child, parts + name, out, emitted)
        }
        emitted += className
        out += "class $className:"
        node.children.toSortedMap().forEach { (name, child) ->
            child.coordinates?.let { coords -> out += "    $name = ScreenRatio(${coords.joinToString(", ") { pyNumber(it) }})" }
        }
        out += ""
        out += "    def __init__(self, parent):"
        out += "        self._parent = parent"
        node.children.toSortedMap().forEach { (name, child) ->
            if (child.children.isNotEmpty()) out += "        self.$name = ${className(parts + name)}(parent)"
        }
        out += ""
        out += ""
    }

    private fun className(parts: List<String>): String {
        if (parts == listOf("screen")) return "ScreenPosition"
        return parts.joinToString("") { part -> part.split(Regex("[^A-Za-z0-9]+"))
            .filter { it.isNotEmpty() }
            .joinToString("") { token -> token.replaceFirstChar { c -> c.uppercase() } } } + "Position"
    }

    private fun pyNumber(value: Double): String = if (value % 1.0 == 0.0) String.format(Locale.ROOT, "%.1f", value) else value.toString()
    private fun round(value: Double): Double = String.format(Locale.ROOT, "%.${DECIMALS}f", value).toDouble()
}

@Service(Service.Level.PROJECT)
class PositionPublisherService(private val project: Project) {
    enum class Format { JSON, PYTHON }
    data class Result(val errors: List<String> = emptyList(), val conflicts: List<Path> = emptyList(), val written: List<Path> = emptyList())

    fun collect(): PositionResource.PublishResult {
        val boxes = project.service<BoxCatalogService>().readAuthoring()
        val points = project.service<PointCatalogService>().read()
        if (points.errors.isNotEmpty()) return PositionResource.PublishResult(emptyList(), points.errors.map { "point:$it" })
        val imageMap = linkedMapOf<String, PositionResource.Image>()
        val root = project.service<OkProjectDataService>().rootPath()
        val templates = OkScriptToolkitSettings.getInstance(project).okTemplatesDirectory()
        fun resolved(file: String, fallbackW: Int, fallbackH: Int): PositionResource.Image {
            val path = root?.resolve(templates)?.resolve(file)
            val actual = path?.toFile()?.let { project.service<TemplateAssetDataService>().readImageHeaderSize(it) }
            return PositionResource.Image(file, actual?.first ?: fallbackW, actual?.second ?: fallbackH)
        }
        boxes.images.forEach { image -> imageMap[image.file.lowercase()] = resolved(image.file, image.width, image.height) }
        points.file.images.forEach { image -> imageMap[image.file.lowercase()] = resolved(image.file, image.width, image.height) }
        val items = mutableListOf<PositionResource.Item>()
        boxes.boxes.forEach { box ->
            items += PositionResource.Item(box.path, box.image, PositionResource.Kind.RECT, box.bbox[0], box.bbox[1], box.bbox[2], box.bbox[3])
        }
        points.file.points.forEach { point ->
            items += PositionResource.Item(point.path, point.image, PositionResource.Kind.POINT, point.x, point.y)
        }
        return PositionResource.publish(items, imageMap.values.toList())
    }

    fun publish(format: Format, overwriteHandwritten: Boolean = false): Result {
        val published = collect()
        if (published.errors.isNotEmpty()) return Result(errors = published.errors)
        val root = project.service<OkProjectDataService>().rootPath() ?: return Result(errors = listOf("root"))
        val scene = root.resolve("src").resolve("scene")
        return when (format) {
            Format.JSON -> {
                val target = scene.resolve("positions.json")
                if (!writeAnnotationText(target, PositionResource.serializeJson(published))) Result(errors = listOf("write"))
                else Result(written = listOf(target))
            }
            Format.PYTHON -> {
                val screen = scene.resolve("ScreenRatio.py")
                val map = scene.resolve("PositionMap.py")
                val conflicts = listOf(screen, map).filter { Files.isRegularFile(it) && !runCatching { Files.readString(it).startsWith(PositionResource.GENERATED_MARKER) }.getOrDefault(false) }
                if (conflicts.isNotEmpty() && !overwriteHandwritten) return Result(conflicts = conflicts)
                val ok1 = writeAnnotationText(screen, PositionResource.serializeScreenRatioPython())
                val ok2 = writeAnnotationText(map, PositionResource.serializePositionMapPython(published))
                if (!ok1 || !ok2) Result(errors = listOf("write")) else Result(written = listOf(screen, map))
            }
        }
    }
}
