package com.alicejump.okscripttoolkit.core

import com.alicejump.okscripttoolkit.settings.OkScriptToolkitSettings
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

/** 框和点在最终 PositionMap 命名空间中的统一运行时表示。 */
object PositionResource {
    enum class Kind { RECT, POINT }
    data class Image(val file: String, val width: Int, val height: Int)
    data class Item(
        val path: String,
        val image: String,
        val kind: Kind,
        val x: Int,
        val y: Int,
        val w: Int = 0,
        val h: Int = 0,
    )
    data class RuntimePosition(val path: String, val coordinates: List<Double>)
    data class PublishResult(val positions: List<RuntimePosition>, val errors: List<String>)

    private const val DECIMALS = 6
    const val GENERATED_MARKER = "# Generated by ok-script-toolkit. Do not edit manually."

    fun publish(items: List<Item>, images: List<Image>): PublishResult {
        val errors = mutableListOf<String>()
        val positions = mutableListOf<RuntimePosition>()
        val seen = mutableSetOf<String>()
        val imageMap = images.associateBy { it.file.lowercase(Locale.ROOT) }
        for (item in items) {
            val path = item.path.trim()
            val pathError = PointCatalogService.positionPathError(path)
            if (pathError != null) { errors += "$pathError:$path"; continue }
            if (!seen.add(path)) { errors += "duplicate:$path"; continue }
            if (seen.any { it != path && (it.startsWith("$path.") || path.startsWith("$it.")) }) {
                errors += "prefix:$path"
                continue
            }
            val image = imageMap[item.image.lowercase(Locale.ROOT)]
            if (image == null) { errors += "image:$path"; continue }
            val coordinates = when (item.kind) {
                Kind.POINT -> normalizePoint(item.x, item.y, image.width, image.height)
                Kind.RECT -> normalizeRect(item.x, item.y, item.w, item.h, image.width, image.height)
            }
            if (coordinates == null) { errors += "geometry:$path"; continue }
            positions += RuntimePosition(path, coordinates)
        }
        return PublishResult(positions.sortedBy { it.path }, errors)
    }

    fun normalizePoint(x: Int, y: Int, width: Int, height: Int): List<Double>? {
        if (width <= 0 || height <= 0 || x < 0 || y < 0 || x > width || y > height) return null
        return listOf(round(x.toDouble() / width), round(y.toDouble() / height))
    }

    fun normalizeRect(x: Int, y: Int, w: Int, h: Int, width: Int, height: Int): List<Double>? {
        if (width <= 0 || height <= 0 || w <= 0 || h <= 0 || x < 0 || y < 0 || x + w > width || y + h > height) return null
        return listOf(
            round(x.toDouble() / width),
            round(y.toDouble() / height),
            round((x + w).toDouble() / width),
            round((y + h).toDouble() / height),
        )
    }

    fun serializeJson(result: PublishResult): String {
        val mapper = ObjectMapper()
        val root = mapper.createObjectNode().put("version", 2)
        val array = mapper.createArrayNode()
        result.positions.sortedBy { it.path }.forEach { position ->
            val node = mapper.createObjectNode().put("path", position.path)
            val coords = mapper.createArrayNode()
            position.coordinates.forEach(coords::add)
            node.set<JsonNode>("coordinates", coords)
            array.add(node)
        }
        root.set<JsonNode>("positions", array)
        return root.toPrettyString() + "\n"
    }

    fun serializeScreenRatioPython(): String = """$GENERATED_MARKER
from typing import TYPE_CHECKING, Iterator

if TYPE_CHECKING:
    from ok import Box


class ScreenRatio:
    '''A normalized screen point (x, y) or rectangle (left, top, right, bottom).'''

    def __init__(self, *coordinates: float):
        if len(coordinates) not in (2, 4):
            raise ValueError("ScreenRatio requires either 2 point coordinates or 4 rect coordinates")
        self.coordinates = tuple(coordinates)
        self.name: str | None = None

    def __set_name__(self, owner: type, field_name: str):
        self.name = f"{owner.__name__}.{field_name}"

    def __get__(self, instance, owner):
        if instance is None:
            return self
        return BoundScreenRatio(self, instance._parent)

    def __iter__(self) -> Iterator[float]:
        return iter(self.coordinates)

    @property
    def is_rect(self) -> bool:
        return len(self.coordinates) == 4

    def _to_box(self, parent) -> "Box":
        if not self.is_rect:
            raise ValueError("Only a rect ScreenRatio can be converted to a Box")
        return parent.box_of_screen(*self.coordinates, name=self.name or "ScreenRatio", hcenter=True)


class BoundScreenRatio:
    def __init__(self, ratio: ScreenRatio, parent):
        self.ratio = ratio
        self.parent = parent

    def __iter__(self) -> Iterator[float]:
        return iter(self.ratio)

    def to_box(self) -> "Box":
        return self.ratio._to_box(self.parent)
""".trimIndent() + "\n"

    fun serializePositionMapPython(result: PublishResult): String {
        val root = Node()
        for (position in result.positions.sortedBy { it.path }) {
            var node = root
            position.path.split('.').forEach { part -> node = node.children.getOrPut(part) { Node() } }
            node.coordinates = position.coordinates
        }
        val out = mutableListOf(
            GENERATED_MARKER,
            "from .ScreenRatio import ScreenRatio",
            "",
            "",
        )
        val emitted = mutableSetOf<String>()
        root.children.toSortedMap().forEach { (name, child) -> emitClass(child, listOf(name), out, emitted) }
        out += "class PositionMap:"
        out += "    def __init__(self, parent):"
        if (root.children.isEmpty()) out += "        pass"
        else root.children.toSortedMap().forEach { (name, _) -> out += "        self.$name = ${className(listOf(name))}(parent)" }
        out += ""
        return out.joinToString("\n") + "\n"
    }

    private data class Node(val children: MutableMap<String, Node> = mutableMapOf(), var coordinates: List<Double>? = null)

    private fun emitClass(node: Node, parts: List<String>, out: MutableList<String>, emitted: MutableSet<String>) {
        val className = className(parts)
        if (className in emitted) return
        node.children.toSortedMap().forEach { (name, child) ->
            if (child.children.isNotEmpty()) emitClass(child, parts + name, out, emitted)
        }
        emitted += className
        out += "class $className:"
        node.children.toSortedMap().forEach { (name, child) ->
            child.coordinates?.let { coords -> out += "    $name = ScreenRatio(${coords.joinToString(", ") { pyNumber(it) }})" }
        }
        out += ""
        out += "    def __init__(self, parent):"
        out += "        self._parent = parent"
        node.children.toSortedMap().forEach { (name, child) ->
            if (child.children.isNotEmpty()) out += "        self.$name = ${className(parts + name)}(parent)"
        }
        out += ""
        out += ""
    }

    private fun className(parts: List<String>): String {
        if (parts == listOf("screen")) return "ScreenPosition"
        return "Position_" + parts.joinToString("__") { part -> "${part.length}_$part" }
    }

    private fun pyNumber(value: Double): String =
        if (value % 1.0 == 0.0) String.format(Locale.ROOT, "%.1f", value) else value.toString()

    private fun round(value: Double): Double = String.format(Locale.ROOT, "%.${DECIMALS}f", value).toDouble()
}

/** Conflicts in the single exported PositionMap namespace, independent of authoring resource kind. */
internal fun positionNamespaceConflicts(selectedPaths: Collection<String>, otherPaths: Collection<String>): List<String> {
    val errors = linkedSetOf<String>()
    for (selectedRaw in selectedPaths) {
        val selected = selectedRaw.trim()
        if (selected.isEmpty()) continue
        for (otherRaw in otherPaths) {
            val other = otherRaw.trim()
            if (other.isEmpty()) continue
            when {
                selected == other -> errors += "duplicate:$selected"
                selected.startsWith("$other.") || other.startsWith("$selected.") -> errors += "prefix:$selected"
            }
        }
    }
    return errors.toList()
}

@Service(Service.Level.PROJECT)
class PositionPublisherService(private val project: Project) {
    enum class Format { JSON, PYTHON }
    data class Selection(val rect: Boolean, val point: Boolean) {
        val any: Boolean get() = rect || point
    }
    data class Result(val errors: List<String> = emptyList(), val conflicts: List<Path> = emptyList(), val written: List<Path> = emptyList())

    fun collect(): PositionResource.PublishResult = collect(Selection(rect = true, point = true))

    fun collect(selection: Selection): PositionResource.PublishResult {
        if (!selection.any) return PositionResource.PublishResult(emptyList(), listOf("selection"))

        val imageMap = linkedMapOf<String, PositionResource.Image>()
        val items = mutableListOf<PositionResource.Item>()
        val root = project.service<OkProjectDataService>().rootPath()
        val templates = OkScriptToolkitSettings.getInstance(project).okTemplatesDirectory()
        fun resolved(file: String, fallbackW: Int, fallbackH: Int): PositionResource.Image {
            val path = root?.resolve(templates)?.resolve(file)
            val actual = path?.toFile()?.let { project.service<TemplateAssetDataService>().readImageHeaderSize(it) }
            return PositionResource.Image(file, actual?.first ?: fallbackW, actual?.second ?: fallbackH)
        }

        if (selection.rect) {
            val boxCatalog = project.service<BoxCatalogService>()
            val boxErrors = boxCatalog.authoringErrors()
            if (boxErrors.isNotEmpty()) return PositionResource.PublishResult(emptyList(), boxErrors.map { "box:$it" })
            val boxes = boxCatalog.readAuthoring()
            boxes.images.forEach { image -> imageMap[image.file.lowercase()] = resolved(image.file, image.width, image.height) }
            boxes.boxes.forEach { box ->
                items += PositionResource.Item(box.path, box.image, PositionResource.Kind.RECT, box.bbox[0], box.bbox[1], box.bbox[2], box.bbox[3])
            }
        }

        if (selection.point) {
            val points = project.service<PointCatalogService>().read()
            if (points.errors.isNotEmpty()) return PositionResource.PublishResult(emptyList(), points.errors.map { "point:$it" })
            points.file.images.forEach { image -> imageMap[image.file.lowercase()] = resolved(image.file, image.width, image.height) }
            points.file.points.forEach { point ->
                items += PositionResource.Item(point.path, point.image, PositionResource.Kind.POINT, point.x, point.y)
            }
        }

        // Partial publishing replaces the complete output. Check the shared namespace against a
        // readable unselected catalog, but never let errors in an intentionally unselected source
        // block the selected resource type.
        if (selection.rect != selection.point) {
            val selectedPaths = items.map { it.path }
            val otherPaths = if (selection.rect) {
                val points = project.service<PointCatalogService>().read()
                if (points.errors.isEmpty()) points.file.points.map { it.path } else emptyList()
            } else {
                val boxes = project.service<BoxCatalogService>()
                if (boxes.authoringErrors().isEmpty()) boxes.readAuthoring().boxes.map { it.path } else emptyList()
            }
            val namespaceErrors = positionNamespaceConflicts(selectedPaths, otherPaths)
            if (namespaceErrors.isNotEmpty()) return PositionResource.PublishResult(emptyList(), namespaceErrors)
        }

        return PositionResource.publish(items, imageMap.values.toList())
    }

    private fun sceneDirectory(root: Path): Path? {
        val normalizedRoot = root.toAbsolutePath().normalize()
        val realRoot = runCatching { normalizedRoot.toRealPath() }.getOrNull() ?: return null
        val scene = normalizedRoot.resolve("src").resolve("scene")
        val existing = generateSequence(scene) { it.parent }.firstOrNull { Files.exists(it) } ?: return null
        val realExisting = runCatching { existing.toRealPath() }.getOrNull() ?: return null
        if (!realExisting.startsWith(realRoot)) return null
        return scene
    }

    fun publish(format: Format, overwriteHandwritten: Boolean = false): Result =
        publish(format, Selection(rect = true, point = true), overwriteHandwritten)

    fun publish(format: Format, selection: Selection, overwriteHandwritten: Boolean = false): Result {
        val published = collect(selection)
        if (published.errors.isNotEmpty()) return Result(errors = published.errors)
        if (published.positions.isEmpty()) return Result(errors = listOf("empty"))
        val root = project.service<OkProjectDataService>().rootPath() ?: return Result(errors = listOf("root"))
        val scene = sceneDirectory(root) ?: return Result(errors = listOf("outside"))
        return when (format) {
            Format.JSON -> {
                val target = scene.resolve("positions.json")
                if (!writeAnnotationText(target, PositionResource.serializeJson(published))) Result(errors = listOf("write"))
                else Result(written = listOf(target))
            }
            Format.PYTHON -> {
                val screen = scene.resolve("ScreenRatio.py")
                val map = scene.resolve("PositionMap.py")
                val conflicts = listOf(screen, map).filter {
                    Files.isRegularFile(it) && !runCatching {
                        Files.readString(it).startsWith(PositionResource.GENERATED_MARKER)
                    }.getOrDefault(false)
                }
                if (conflicts.isNotEmpty() && !overwriteHandwritten) return Result(conflicts = conflicts)

                val screenSource = PositionResource.serializeScreenRatioPython()
                val mapSource = PositionResource.serializePositionMapPython(published)
                val screenExisted = Files.isRegularFile(screen)
                val previousScreen = if (screenExisted) {
                    runCatching { Files.readAllBytes(screen) }.getOrElse {
                        return Result(errors = listOf("backup:ScreenRatio.py"))
                    }
                } else null
                if (!writeAnnotationText(screen, screenSource)) return Result(errors = listOf("write:ScreenRatio.py"))
                if (!writeAnnotationText(map, mapSource)) {
                    val restored = if (previousScreen == null) {
                        runCatching { Files.deleteIfExists(screen); true }.getOrDefault(false)
                    } else {
                        runCatching { Files.write(screen, previousScreen); true }.getOrDefault(false)
                    }
                    return Result(errors = listOf(if (restored) "write:PositionMap.py" else "write:PositionMap.py:rollback"))
                }
                Result(written = listOf(screen, map))
            }
        }
    }
}
