# -*- coding: utf-8 -*-
"""角色面板注入强化组编辑（对齐用户已实现的技能 CRUD 风格）。"""
import io

p = 'src/main/kotlin/com/alicejump/okscripttoolkit/ui/CharacterToolWindowFactory.kt'
with io.open(p, encoding='utf-8', newline='') as f:
    src = f.read().replace('\r\n', '\n')

old = '''        val deleteSkillAction = ToolbarAction(AllIcons.Actions.GC, OkScriptToolkitBundle.message("characterManager.deleteSkill")) { deleteSelectedSkill() }
        val actionGroup = com.intellij.openapi.actionSystem.DefaultActionGroup(
            refreshAction, addSkillAction, editSkillAction, deleteSkillAction,
        )'''
new = '''        val deleteSkillAction = ToolbarAction(AllIcons.Actions.GC, OkScriptToolkitBundle.message("characterManager.deleteSkill")) { deleteSelectedSkill() }
        val enhancementAction = ToolbarAction(AllIcons.Actions.Diff, OkScriptToolkitBundle.message("characterManager.enhancements")) { runEnhancementFlow() }
        val actionGroup = com.intellij.openapi.actionSystem.DefaultActionGroup(
            refreshAction, addSkillAction, editSkillAction, deleteSkillAction, enhancementAction,
        )'''
assert old in src, 'toolbar anchor'
src = src.replace(old, new, 1)

anchor = '''    override fun dispose() {}
}'''

method_parts = []
method_parts.append('    // ---- Enhancement editing ----')
method_parts.append('')
method_parts.append('    private enum class EnhancementAction { ADD, EDIT, DELETE }')
method_parts.append('')
method_parts.append('    private fun runEnhancementFlow() {')
method_parts.append('        val row = characterTable.selectedRow')
method_parts.append('        if (row < 0 || row >= currentCharacters.size) {')
method_parts.append('            com.intellij.openapi.ui.Messages.showInfoMessage(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.selectCharacterFirst"),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            )')
method_parts.append('            return')
method_parts.append('        }')
method_parts.append('        val char = currentCharacters[row]')
method_parts.append('        val path = skillFilePaths[char.characterId]')
method_parts.append('        if (path == null) {')
method_parts.append('            com.intellij.openapi.ui.Messages.showInfoMessage(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.noSkillFile", char.name),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            )')
method_parts.append('            return')
method_parts.append('        }')
method_parts.append('        if (char.skills.isEmpty()) {')
method_parts.append('            com.intellij.openapi.ui.Messages.showInfoMessage(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.noSkills", char.name),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            )')
method_parts.append('            return')
method_parts.append('        }')
method_parts.append('')
method_parts.append('        val skillNames = char.skills.map { "${it.name} (${it.skillId})" }.toTypedArray()')
method_parts.append('        val skillIndex = com.intellij.openapi.ui.Messages.showChooseDialog(')
method_parts.append('            project,')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.enhancementSkillPrompt"),')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            com.intellij.icons.AllIcons.General.Information,')
method_parts.append('            skillNames,')
method_parts.append('            skillNames.firstOrNull(),')
method_parts.append('        )')
method_parts.append('        if (skillIndex < 0) return')
method_parts.append('        val skill = char.skills[skillIndex]')
method_parts.append('        val skillId = skill.skillId')
method_parts.append('')
method_parts.append('        val actions = arrayOf(')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.addEnhancement"),')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.editEnhancement"),')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.deleteEnhancement"),')
method_parts.append('        )')
method_parts.append('        val actionIndex = com.intellij.openapi.ui.Messages.showChooseDialog(')
method_parts.append('            project,')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.enhancementActionPrompt", skill.name),')
method_parts.append('            OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            com.intellij.icons.AllIcons.General.Information,')
method_parts.append('            actions,')
method_parts.append('            actions.firstOrNull(),')
method_parts.append('        )')
method_parts.append('        if (actionIndex < 0) return')
method_parts.append('        val action = EnhancementAction.values()[actionIndex]')
method_parts.append('')
method_parts.append('        val enhCount = skill.enhancements.size')
method_parts.append('        if (action != EnhancementAction.ADD && enhCount == 0) {')
method_parts.append('            com.intellij.openapi.ui.Messages.showInfoMessage(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.noEnhancements", skill.name),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('            )')
method_parts.append('            return')
method_parts.append('        }')
method_parts.append('')
method_parts.append('        var enhancementIndex: Int? = null')
method_parts.append('        if (action != EnhancementAction.ADD) {')
method_parts.append('            val enhNames = skill.enhancements.map { it.name }.toTypedArray()')
method_parts.append('            val enhIdx = com.intellij.openapi.ui.Messages.showChooseDialog(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancementPickPrompt"),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.enhancements"),')
method_parts.append('                com.intellij.icons.AllIcons.General.Information,')
method_parts.append('                enhNames,')
method_parts.append('                enhNames.firstOrNull(),')
method_parts.append('            )')
method_parts.append('            if (enhIdx < 0) return')
method_parts.append('            enhancementIndex = enhIdx')
method_parts.append('        }')
method_parts.append('')
method_parts.append('        var form: Map<String, String> = emptyMap()')
method_parts.append('        if (action != EnhancementAction.DELETE) {')
method_parts.append('            val existing = skill.enhancements.getOrNull(enhancementIndex ?: -1)')
method_parts.append('            val dialog = EnhancementDialog(project, existing?.name, existing?.triggerText)')
method_parts.append('            if (!dialog.showAndGet()) return')
method_parts.append('            form = dialog.formValues()')
method_parts.append('        } else {')
method_parts.append('            val confirm = com.intellij.openapi.ui.Messages.showYesNoDialog(')
method_parts.append('                project,')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.deleteEnhancementConfirm", skill.enhancements[enhancementIndex!!].name),')
method_parts.append('                OkScriptToolkitBundle.message("characterManager.deleteEnhancement"),')
method_parts.append('                com.intellij.openapi.ui.Messages.getWarningIcon(),')
method_parts.append('            )')
method_parts.append('            if (confirm != com.intellij.openapi.ui.Messages.YES) return')
method_parts.append('        }')
method_parts.append('')
method_parts.append('        CompletableFuture.runAsync {')
method_parts.append('            try {')
method_parts.append('                when (action) {')
method_parts.append('                    EnhancementAction.ADD -> com.alicejump.okscripttoolkit.core.CharacterDataMutations.addEnhancement(path, skillId, form)')
method_parts.append('                    EnhancementAction.EDIT -> com.alicejump.okscripttoolkit.core.CharacterDataMutations.updateEnhancement(path, skillId, enhancementIndex!!, form)')
method_parts.append('                    EnhancementAction.DELETE -> com.alicejump.okscripttoolkit.core.CharacterDataMutations.deleteEnhancement(path, skillId, enhancementIndex!!)')
method_parts.append('                }')
method_parts.append('                SwingUtilities.invokeLater { loadData() }')
method_parts.append('            } catch (e: Exception) {')
method_parts.append('                SwingUtilities.invokeLater {')
method_parts.append('                    com.intellij.openapi.ui.Messages.showErrorDialog(')
method_parts.append('                        project, e.message ?: e.toString(),')
method_parts.append('                        OkScriptToolkitBundle.message("characterManager.mutationFailed"),')
method_parts.append('                    )')
method_parts.append('                }')
method_parts.append('            }')
method_parts.append('        }')
method_parts.append('    }')
method = '\n'.join(method_parts)

dialog_parts = []
dialog_parts.append('')
dialog_parts.append('/**')
dialog_parts.append(' * Enhancement editing form (name / trigger_text / enhancement_effect).')
dialog_parts.append(' */')
dialog_parts.append('class EnhancementDialog(')
dialog_parts.append('    project: Project,')
dialog_parts.append('    initialName: String?,')
dialog_parts.append('    initialTrigger: String?,')
dialog_parts.append(') : com.intellij.openapi.ui.DialogWrapper(project) {')
dialog_parts.append('')
dialog_parts.append('    private val nameField = javax.swing.JTextField(initialName ?: "")')
dialog_parts.append('    private val triggerField = javax.swing.JTextField(initialTrigger ?: "")')
dialog_parts.append('    private val effectField = javax.swing.JTextField()')
dialog_parts.append('')
dialog_parts.append('    init {')
dialog_parts.append('        title = OkScriptToolkitBundle.message("characterManager.enhancements")')
dialog_parts.append('        init()')
dialog_parts.append('    }')
dialog_parts.append('')
dialog_parts.append('    override fun createCenterPanel(): JComponent {')
dialog_parts.append('        val form = JPanel(java.awt.GridBagLayout())')
dialog_parts.append('        var row = 0')
dialog_parts.append('        fun addField(label: String, comp: JComponent) {')
dialog_parts.append('            form.add(JLabel(label), java.awt.GridBagConstraints().apply {')
dialog_parts.append('                gridx = 0; gridy = row; anchor = java.awt.GridBagConstraints.WEST')
dialog_parts.append('                insets = java.awt.Insets(3, 6, 3, 4)')
dialog_parts.append('            })')
dialog_parts.append('            form.add(comp, java.awt.GridBagConstraints().apply {')
dialog_parts.append('                gridx = 1; gridy = row; fill = java.awt.GridBagConstraints.HORIZONTAL')
dialog_parts.append('                weightx = 1.0')
dialog_parts.append('                insets = java.awt.Insets(3, 4, 3, 6)')
dialog_parts.append('            })')
dialog_parts.append('            row++')
dialog_parts.append('        }')
dialog_parts.append('        addField(OkScriptToolkitBundle.message("characterManager.fieldEnhName"), nameField)')
dialog_parts.append('        addField(OkScriptToolkitBundle.message("characterManager.fieldTriggerText"), triggerField)')
dialog_parts.append('        addField(OkScriptToolkitBundle.message("characterManager.fieldEnhEffect"), effectField)')
dialog_parts.append('        return form')
dialog_parts.append('    }')
dialog_parts.append('')
dialog_parts.append('    fun formValues(): Map<String, String> = mapOf(')
dialog_parts.append('        "name" to nameField.text.trim(),')
dialog_parts.append('        "trigger_text" to triggerField.text.trim(),')
dialog_parts.append('        "enhancement_effect" to effectField.text.trim(),')
dialog_parts.append('        "effects" to "",')
dialog_parts.append('    )')
dialog_parts.append('}')
dialog = '\n'.join(dialog_parts)

assert anchor in src, 'dispose anchor'
src = src.replace(anchor, method + '\n\n    override fun dispose() {}\n}' + dialog, 1)

with io.open(p, 'w', encoding='utf-8', newline='\n') as f:
    f.write(src)
print('enhancement UI injected')
